# Generated by Django 5.2.8 on 2025-11-26 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Optional parent category for hierarchical organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit identifier for this product', max_length=100)),
                ('brand', models.CharField(blank=True, help_text='Brand or manufacturer of the product', max_length=100)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(db_index=True, default=0, help_text='Available stock when the product has no variations')),
                ('in_stock', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the attribute (e.g., 'Color', 'Size')", max_length=50)),
                ('value', models.CharField(help_text="Value of the attribute (e.g., 'Red', 'XL')", max_length=50)),
                ('sku', models.CharField(blank=True, help_text='Unique SKU for this specific variation', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Override base price for this variation', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Stock quantity available for this variation')),
                ('in_stock', models.BooleanField(default=True, help_text='Whether the variation is currently available')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='catalog.product')),
            ],
            options={
                'ordering': ['product', 'name', 'value'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='catalog_cat_name_39f70b_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='catalog_cat_slug_695af4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='catalog_pro_price_2d2a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['in_stock', 'price'], name='catalog_pro_in_stoc_18ac32_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'price'], name='catalog_pro_categor_5a4a66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'name', 'value')},
        ),
    ]
